language: ruby
bundler_args: --without development --path=~/.bundle
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - sudo apt-get install libicu-dev -y
  - "bundle config build.nokogiri --use-system-libraries"
  - gem install bundler bundle_cache
  - bundle_cache_install
after_script:
- bundle_cache
env:
  global:
    - BUNDLE_ARCHIVE="gitlab-ci-bundler-archive"
    - AWS_S3_BUCKET="gitlab_com_bundle_cache_travis_ci"
    - AWS_ACCESS_KEY_ID="AKIAISHUQBQQINXNMA5Q"
    - AWS_SECRET_ACCESS_KEY="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"
    - RAILS_ENV=test
    - TRAVIS=true
  matrix:
    - TASK=spinach_project DB=mysql
    - TASK=spinach_other DB=mysql
    - TASK=spec:api DB=mysql
    - TASK=spec:feature DB=mysql
    - TASK=spec:other DB=mysql
    - TASK=jasmine:ci DB=mysql
    - TASK=spinach_project DB=postgresql
    - TASK=spinach_other DB=postgresql
    - TASK=spec:api DB=postgresql
    - TASK=spec:feature DB=postgresql
    - TASK=spec:other DB=postgresql
    - TASK=jasmine:ci DB=postgresql
rvm:
  - 2.1.2
services:
  - redis-server
before_script:
  - "cp config/database.yml.$DB config/database.yml"
  - "cp config/gitlab.yml.example config/gitlab.yml"
  - "bundle exec rake db:create"
script: "bundle exec rake $TASK --trace"
notifications:
  email: false
git:
  depth: 10
